#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER "$API_DB_USER" WITH PASSWORD '$API_DB_PASSWORD';
CREATE DATABASE "$API_DB_NAME";
GRANT ALL PRIVILEGES ON DATABASE "$API_DB_NAME" TO "$API_DB_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$API_DB_NAME" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS timescaledb;
    CREATE EXTENSION IF NOT EXISTS vector;
    GRANT ALL PRIVILEGES ON SCHEMA public TO "$API_DB_USER";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$API_DB_USER";
EOSQL
